# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa02f77c111be3c909d45124c1ad0d90ee94e1a1d3d0e03ac3af529dbb50f509b55974066286db101134992fd13c57e07ca176356cf7b29a19a61124852ac5e8

test:
  secret_key_base: 159cfedac61f6bed6b422d3ab77820492766c13501c98c430afadd999b2478ba611c839521b3fd2b7fa6c06b152ea96474b9764665e90af21fac86bfeef3fcbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
