Comment.create!(restaurant_id: 209, user_id: 4, message: 'at risus. Nunc ac sem ut dolor dapibus gravida.')
Comment.create!(restaurant_id: 234, user_id: 7, message: 'magna tellus faucibus leo, in lobortis tellus justo sit amet nulla.')
Comment.create!(restaurant_id: 282, user_id: 1, message: 'eget laoreet posuere, enim nisl elementum purus,')
Comment.create!(restaurant_id: 256, user_id: 2, message: 'a, facilisis non,')
Comment.create!(restaurant_id: 290, user_id: 1, message: 'in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus.')
Comment.create!(restaurant_id: 249, user_id: 3, message: 'Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec')
Comment.create!(restaurant_id: 293, user_id: 4, message: 'metus facilisis lorem tristique aliquet.')
Comment.create!(restaurant_id: 244, user_id: 6, message: 'neque vitae semper egestas, urna')
Comment.create!(restaurant_id: 299, user_id: 1, message: 'lorem eu metus. In lorem. Donec elementum, lorem')
Comment.create!(restaurant_id: 289, user_id: 2, message: 'Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna.')
Comment.create!(restaurant_id: 221, user_id: 6, message: 'faucibus id, libero. Donec consectetuer')
Comment.create!(restaurant_id: 250, user_id: 7, message: 'imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi')
Comment.create!(restaurant_id: 283, user_id: 1, message: 'vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus,')
Comment.create!(restaurant_id: 221, user_id: 3, message: 'sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus')
Comment.create!(restaurant_id: 241, user_id: 6, message: 'lacus pede sagittis augue, eu tempor erat')
Comment.create!(restaurant_id: 231, user_id: 3, message: 'Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean')
Comment.create!(restaurant_id: 257, user_id: 7, message: 'egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui.')
Comment.create!(restaurant_id: 240, user_id: 2, message: 'quis turpis vitae purus gravida sagittis. Duis gravida. Praesent')
Comment.create!(restaurant_id: 220, user_id: 2, message: 'metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam')
Comment.create!(restaurant_id: 275, user_id: 1, message: 'pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod')
Comment.create!(restaurant_id: 250, user_id: 1, message: 'semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam')
Comment.create!(restaurant_id: 246, user_id: 6, message: 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae')
Comment.create!(restaurant_id: 211, user_id: 4, message: 'per conubia nostra, per inceptos hymenaeos.')
Comment.create!(restaurant_id: 260, user_id: 7, message: 'magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus')
Comment.create!(restaurant_id: 293, user_id: 2, message: 'a mi fringilla mi lacinia')
Comment.create!(restaurant_id: 223, user_id: 3, message: 'risus a ultricies adipiscing, enim mi tempor lorem, eget mollis lectus pede')
Comment.create!(restaurant_id: 281, user_id: 6, message: 'mattis. Integer eu')
Comment.create!(restaurant_id: 262, user_id: 6, message: 'sit amet risus.')
Comment.create!(restaurant_id: 272, user_id: 3, message: 'Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo.')
Comment.create!(restaurant_id: 253, user_id: 2, message: 'dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet.')
Comment.create!(restaurant_id: 287, user_id: 2, message: 'justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at')
Comment.create!(restaurant_id: 286, user_id: 6, message: 'at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur')
Comment.create!(restaurant_id: 293, user_id: 3, message: 'Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus')
Comment.create!(restaurant_id: 267, user_id: 7, message: 'natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla')
Comment.create!(restaurant_id: 284, user_id: 4, message: 'nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat')
Comment.create!(restaurant_id: 249, user_id: 6, message: 'vehicula risus. Nulla eget')
Comment.create!(restaurant_id: 283, user_id: 4, message: 'augue id ante dictum')
Comment.create!(restaurant_id: 295, user_id: 4, message: 'parturient montes, nascetur ridiculus mus. Donec dignissim magna a')
Comment.create!(restaurant_id: 268, user_id: 3, message: 'eget, dictum placerat, augue.')
Comment.create!(restaurant_id: 290, user_id: 4, message: 'accumsan neque et nunc. Quisque ornare')
Comment.create!(restaurant_id: 294, user_id: 4, message: 'per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus.')
Comment.create!(restaurant_id: 288, user_id: 1, message: 'dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce')
Comment.create!(restaurant_id: 291, user_id: 2, message: 'aliquet, sem ut cursus')
Comment.create!(restaurant_id: 297, user_id: 3, message: 'Sed eu nibh vulputate mauris sagittis placerat. Cras')
Comment.create!(restaurant_id: 250, user_id: 4, message: 'fringilla ornare placerat, orci lacus vestibulum')
Comment.create!(restaurant_id: 236, user_id: 4, message: 'eu enim. Etiam imperdiet dictum')
Comment.create!(restaurant_id: 287, user_id: 3, message: 'Pellentesque ultricies dignissim lacus. Aliquam rutrum')
Comment.create!(restaurant_id: 270, user_id: 1, message: 'Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet.')
Comment.create!(restaurant_id: 212, user_id: 2, message: 'nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus')
Comment.create!(restaurant_id: 295, user_id: 3, message: 'Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant')
Comment.create!(restaurant_id: 218, user_id: 3, message: 'erat semper rutrum. Fusce dolor quam, elementum at,')
Comment.create!(restaurant_id: 223, user_id: 2, message: 'gravida. Aliquam tincidunt, nunc')
Comment.create!(restaurant_id: 218, user_id: 3, message: 'nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer')
Comment.create!(restaurant_id: 211, user_id: 4, message: 'egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu')
Comment.create!(restaurant_id: 242, user_id: 6, message: 'bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare')
Comment.create!(restaurant_id: 238, user_id: 1, message: 'nisi. Cum sociis natoque penatibus et')
Comment.create!(restaurant_id: 262, user_id: 2, message: 'eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin')
Comment.create!(restaurant_id: 254, user_id: 3, message: 'egestas rhoncus. Proin')
Comment.create!(restaurant_id: 212, user_id: 2, message: 'ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor')
Comment.create!(restaurant_id: 277, user_id: 2, message: 'ullamcorper, nisl arcu iaculis enim, sit amet')
Comment.create!(restaurant_id: 255, user_id: 1, message: 'et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida')
Comment.create!(restaurant_id: 211, user_id: 1, message: 'sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi.')
Comment.create!(restaurant_id: 217, user_id: 4, message: 'in consequat enim diam vel')
Comment.create!(restaurant_id: 268, user_id: 2, message: 'molestie arcu. Sed eu')
Comment.create!(restaurant_id: 289, user_id: 3, message: 'facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem,')
Comment.create!(restaurant_id: 268, user_id: 6, message: 'morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed')
Comment.create!(restaurant_id: 299, user_id: 1, message: 'tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae')
Comment.create!(restaurant_id: 227, user_id: 7, message: 'luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl')
Comment.create!(restaurant_id: 276, user_id: 2, message: 'at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et')
Comment.create!(restaurant_id: 265, user_id: 2, message: 'ac arcu. Nunc mauris. Morbi non sapien molestie orci')
Comment.create!(restaurant_id: 276, user_id: 1, message: 'est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum')
Comment.create!(restaurant_id: 223, user_id: 3, message: 'lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci')
Comment.create!(restaurant_id: 266, user_id: 2, message: 'ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus. Curabitur')
Comment.create!(restaurant_id: 245, user_id: 7, message: 'orci. Donec nibh. Quisque nonummy ipsum non')
Comment.create!(restaurant_id: 281, user_id: 3, message: 'pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus')
Comment.create!(restaurant_id: 299, user_id: 4, message: 'nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin')
Comment.create!(restaurant_id: 222, user_id: 6, message: 'arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci. Donec')
Comment.create!(restaurant_id: 246, user_id: 7, message: 'blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id')
Comment.create!(restaurant_id: 298, user_id: 7, message: 'Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit')
Comment.create!(restaurant_id: 251, user_id: 2, message: 'arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;')
Comment.create!(restaurant_id: 262, user_id: 1, message: 'est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed')
Comment.create!(restaurant_id: 236, user_id: 2, message: 'dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum.')
Comment.create!(restaurant_id: 280, user_id: 2, message: 'purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean')
Comment.create!(restaurant_id: 228, user_id: 3, message: 'id ante dictum cursus. Nunc')
Comment.create!(restaurant_id: 280, user_id: 2, message: 'luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis')
Comment.create!(restaurant_id: 259, user_id: 6, message: 'tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula')
Comment.create!(restaurant_id: 237, user_id: 3, message: 'feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit eget')
Comment.create!(restaurant_id: 283, user_id: 1, message: 'laoreet ipsum. Curabitur consequat, lectus sit amet')
Comment.create!(restaurant_id: 260, user_id: 4, message: 'tempor lorem, eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero.')
Comment.create!(restaurant_id: 229, user_id: 1, message: 'sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac')
Comment.create!(restaurant_id: 235, user_id: 6, message: 'adipiscing elit. Aliquam auctor, velit eget laoreet posuere, enim')
Comment.create!(restaurant_id: 209, user_id: 2, message: 'nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae,')
Comment.create!(restaurant_id: 242, user_id: 4, message: 'scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed')
Comment.create!(restaurant_id: 298, user_id: 3, message: 'vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat.')
Comment.create!(restaurant_id: 282, user_id: 6, message: 'velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris')
Comment.create!(restaurant_id: 215, user_id: 4, message: 'Mauris nulla. Integer urna. Vivamus')
Comment.create!(restaurant_id: 256, user_id: 1, message: 'primis in faucibus orci luctus')
Comment.create!(restaurant_id: 215, user_id: 1, message: 'In condimentum. Donec at arcu. Vestibulum')
Comment.create!(restaurant_id: 254, user_id: 1, message: 'fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada')
Comment.create!(restaurant_id: 257, user_id: 6, message: 'Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl.')
