# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Restaurant.delete_all
	
Restaurant.create!(name: 'Lectus Quis Massa', address: '290 Enim. St.', city: 'Kano', state: 'KN', zip: '27723', upvote: 365, downvote: 435)
Restaurant.create!(name: 'Porttitor Interdum', address: '187 Dolor. Ave', city: 'Berlin', state: 'TN', zip: '51733', upvote: 337, downvote: 348)
Restaurant.create!(name: 'Donec Dignissim Magna', address: '7338 Amet St.', city: 'Hoofddorp', state: 'NY.', zip: '72051', upvote: 251, downvote: 496)
Restaurant.create!(name: 'Nonummy', address: '8942 Arcu Street', city: 'Vienna', state: 'NC', zip: '35385', upvote: 17, downvote: 146)
Restaurant.create!(name: 'Cursus', address: '587 Lectus Avenue', city: 'Montague', state: 'CA', zip: '71229', upvote: 472, downvote: 31)
Restaurant.create!(name: 'Aliquam Nec Enim', address: '8745 Egestas, St.', city: 'Petrópolis', state: 'SD de Janeiro', zip: '59501', upvote: 271, downvote: 37)
Restaurant.create!(name: 'Quam', address: '8696 Porttitor St.', city: 'Diadema', state: 'MN', zip: '06459', upvote: 328, downvote: 231)
Restaurant.create!(name: 'Aliquet', address: '594Quam Road', city: 'Neerrepen', state: 'WA', zip: '23716', upvote: 480, downvote: 388)
Restaurant.create!(name: 'Cras Dictum', address: '5889 Donec Street', city: 'Township of Minden Hills', state: 'OR', zip: '15709', upvote: 159, downvote: 469)
Restaurant.create!(name: 'Turpis Vitae', address: '6017 Malesuada Ave', city: 'Boulogne-Billancourt', state: 'IL', zip: '18986', upvote: 391, downvote: 278)
Restaurant.create!(name: 'Nascetur Ridiculus', address: '9643 Est Rd.', city: 'Goulburn', state: 'NJ', zip: '90007', upvote: 476, downvote: 346)
Restaurant.create!(name: 'Velit Aliquam', address: '933Hendrerit Road', city: 'Outremont', state: 'FL', zip: '66461', upvote: 3, downvote: 55)
Restaurant.create!(name: 'Arcu Curabitur', address: '324 Massa. Av.', city: 'Uberaba', state: 'MA', zip: '96506', upvote: 264, downvote: 447)
Restaurant.create!(name: 'Facilisis Vitae', address: '7553 Ante Road', city: 'Aix-en-Provence', state: 'ND', zip: '19086', upvote: 377, downvote: 12)
Restaurant.create!(name: 'Nam Consequat Dolor', address: '1171 In Street', city: 'Galway', state: 'CN', zip: '23109', upvote: 478, downvote: 69)
Restaurant.create!(name: 'Mauris Sapien', address: '7361 Nec, Avenue', city: 'Frasnes-lez-Gosselies', state: 'HI', zip: '78389', upvote: 310, downvote: 256)
Restaurant.create!(name: 'Integer Eu Lacus', address: '1740 Integer St.', city: 'Stargard Szczeciński', state: 'FL', zip: '57174', upvote: 263, downvote: 419)
Restaurant.create!(name: 'Libero Lacus.', address: '9030 Sociis Road', city: 'Galway', state: 'CO', zip: '65616', upvote: 488, downvote: 471)
Restaurant.create!(name: 'Tristique Senectus', address: '565-5938 Et Rd.', city: 'Prince George', state: 'GA', zip: '63797', upvote: 17, downvote: 89)
Restaurant.create!(name: 'Orci', address: '4923 Nec, Road', city: 'Chester', state: 'CA', zip: '30771', upvote: 50, downvote: 196)
Restaurant.create!(name: 'Egestas Ligula', address: '905-5247 Purus St.', city: 'Balclutha', state: 'VA', zip: '91297', upvote: 346, downvote: 378)
Restaurant.create!(name: 'Risus', address: '3260 Aenean Street', city: 'Hoorn', state: 'PN', zip: '67126', upvote: 219, downvote: 401)
Restaurant.create!(name: 'Eleifend Egestas', address: '449-1323 Eu, Ave', city: 'Istanbul', state: 'UT', zip: '82478', upvote: 427, downvote: 394)
Restaurant.create!(name: 'Lacinia', address: '4948 Aliquet Road', city: 'Laon', state: 'PN', zip: '26333', upvote: 116, downvote: 386)
Restaurant.create!(name: 'Integer Tincidunt Aliquam ', address: '4576 Nunc Rd.', city: 'Helmond', state: 'NY', zip: '64016', upvote: 82, downvote: 92)
Restaurant.create!(name: 'Ac', address: '1588 Nam Road', city: 'Portland', state: 'OR', zip: '13567', upvote: 164, downvote: 456)
Restaurant.create!(name: 'Scelerisque', address: '7462 Velit Street', city: 'Saint-Herblain', state: 'TN', zip: '05219', upvote: 193, downvote: 173)
Restaurant.create!(name: 'Elit.', address: '5797 Amet Road', city: 'Sagamu', state: 'CO', zip: '67400', upvote: 195, downvote: 134)
Restaurant.create!(name: 'Sit Amet Orci', address: '3910 Lacus. Av.', city: 'Puntarenas', state: 'UT', zip: '68390', upvote: 136, downvote: 432)
Restaurant.create!(name: 'Lacus Etiam', address: '02 Lacus. St.', city: 'Darbhanga', state: 'DE', zip: '25894', upvote: 334, downvote: 395)
Restaurant.create!(name: 'Id', address: '9703 Fermentum Av.', city: 'Baltimore', state: 'MD', zip: '21436', upvote: 24, downvote: 219)
Restaurant.create!(name: 'Sem Ut Dolor', address: '3049 Porta Rd.', city: 'Okene', state: 'CA', zip: '87031', upvote: 472, downvote: 175)
Restaurant.create!(name: 'Pulvinar Arcu', address: '1355 Fermentum Road', city: 'Spruce Grove', state: 'CO', zip: '97461', upvote: 67, downvote: 383)
Restaurant.create!(name: 'Sem Molestie', address: '7341 Ac St.', city: 'Manukau', state: 'NM', zip: '91237', upvote: 196, downvote: 323)
Restaurant.create!(name: 'Non Luctus', address: '1586 Maecenas St.', city: 'Olsztyn', state: 'CO', zip: '92626', upvote: 195, downvote: 468)
Restaurant.create!(name: 'Aliquam Ultrices Iaculis', address: '4872 Tempor Av.', city: 'Goiânia', state: 'UT', zip: '40418', upvote: 118, downvote: 323)
Restaurant.create!(name: 'Dignissim', address: '5209 At Road', city: 'Kano', state: 'FL', zip: '95759', upvote: 162, downvote: 243)
Restaurant.create!(name: 'Quis', address: '9033 Mattis Av.', city: 'Elsene', state: 'FL', zip: '32935', upvote: 265, downvote: 223)
Restaurant.create!(name: 'Tincidunt Tempus Risus', address: '9080 Vulputate, St.', city: 'Malbaie', state: 'CA', zip: '48092', upvote: 485, downvote: 293)
Restaurant.create!(name: 'Justo', address: '5308 Ante St.', city: 'Qualicum Beach', state: 'AZ', zip: '66370', upvote: 68, downvote: 233)
Restaurant.create!(name: 'Maecenas Mi Felis', address: '2219 Egestas Rd.', city: 'Reyhanlı', state: 'AR', zip: '74830', upvote: 94, downvote: 74)
Restaurant.create!(name: 'Eu Accumsan', address: '2074 Egestas. Rd.', city: 'Dillingen', state: 'CN', zip: '41467', upvote: 52, downvote: 88)
Restaurant.create!(name: 'Non', address: '3197 Augue St.', city: 'Nagaon', state: 'KY', zip: '88329', upvote: 183, downvote: 44)
Restaurant.create!(name: 'Interdum Libero Dui', address: '1513 Penatibus Rd.', city: 'Strathcona County', state: 'WA', zip: '36848', upvote: 5, downvote: 471)
Restaurant.create!(name: 'Parturient Montes Nascetur', address: '1332 Pharetra. Rd.', city: 'Nederokkerzeel', state: 'LA', zip: '05459', upvote: 109, downvote: 155)
Restaurant.create!(name: 'Facilisis Eget', address: '398 Gravida Av.', city: 'San Rafael', state: 'TN', zip: '85427', upvote: 117, downvote: 281)
Restaurant.create!(name: 'Dui Fusce Aliquam', address: '7142 Nam Street', city: 'Berlin', state: 'AL', zip: '46172', upvote: 212, downvote: 15)
Restaurant.create!(name: 'Vestibulum Nec', address: '3705 Purus. Rd.', city: 'Turrialba', state: 'CA', zip: '76201', upvote: 334, downvote: 356)
Restaurant.create!(name: 'Pharetra', address: '4570 A, Rd.', city: 'Strathcona County', state: 'AL', zip: '82628', upvote: 146, downvote: 351)
Restaurant.create!(name: 'Sapien Aenean', address: '8042 Facilisis Rd.', city: 'Vienna', state: 'GA', zip: '62369', upvote: 312, downvote: 106)
Restaurant.create!(name: 'Mi', address: '8992 Malesuada Rd.', city: 'Te Puke', state: 'FL', zip: '59570', upvote: 179, downvote: 463)
Restaurant.create!(name: 'Dictum Eleifend', address: '2134 Ut, Road', city: 'Bari', state: 'MN', zip: '75234', upvote: 320, downvote: 73)
Restaurant.create!(name: 'Sem Ut', address: '5495 Enim. Road', city: 'Whitehorse', state: 'MS', zip: '40938', upvote: 69, downvote: 128)
Restaurant.create!(name: 'Nec', address: '2485 Libero Rd.', city: 'Alajuelita', state: 'SN', zip: '70862', upvote: 315, downvote: 336)
Restaurant.create!(name: 'Quam Quis', address: '8051 Tristique Av.', city: 'Telde', state: 'CN', zip: '87138', upvote: 468, downvote: 94)
Restaurant.create!(name: 'Pede', address: '8560 Metus Avenue', city: 'Sioux City', state: 'IA', zip: '03732', upvote: 382, downvote: 280)
Restaurant.create!(name: 'Convallis', address: '8918 Amet Road', city: 'Saint-Marcel', state: 'NY', zip: '83351', upvote: 324, downvote: 112)
Restaurant.create!(name: 'Egestas Lacinia', address: '164 Auctor Avenue', city: 'Galway', state: 'CA', zip: '22650', upvote: 382, downvote: 323)
Restaurant.create!(name: 'At Libero Morbi', address: '7654 Non Street', city: 'Pulderbos', state: 'NC', zip: '31288', upvote: 464, downvote: 38)
Restaurant.create!(name: 'Convallis Dolor Quisque', address: '4997 A Av.', city: 'Belfast', state: 'CA', zip: '24387', upvote: 91, downvote: 60)
Restaurant.create!(name: 'Ante Maecenas', address: '1637 Felis Street', city: 'New Orleans', state: 'LA', zip: '06144', upvote: 357, downvote: 219)
Restaurant.create!(name: 'Et Magnis Dis', address: '804 Vel St.', city: 'Novoli', state: 'IW', zip: '43131', upvote: 257, downvote: 353)
Restaurant.create!(name: 'Suspendisse', address: '8830 Donec Ave', city: 'Kingston', state: 'ID', zip: '92876', upvote: 247, downvote: 45)
Restaurant.create!(name: 'In Lorem', address: '6149 Magna. St.', city: 'Galway', state: 'CN', zip: '85955', upvote: 40, downvote: 355)
Restaurant.create!(name: 'Interdum', address: '3276 Nec, Avenue', city: 'Russell', state: 'OH', zip: '68870', upvote: 159, downvote: 436)
Restaurant.create!(name: 'Enim Etiam Gravida', address: '3298 In Av.', city: 'Gdynia', state: 'MS', zip: '84330', upvote: 308, downvote: 475)
Restaurant.create!(name: 'Ornare', address: '4293 Iaculis Avenue', city: 'İmamoğlu', state: 'AR', zip: '36654', upvote: 472, downvote: 106)
Restaurant.create!(name: 'Vivamus', address: '5534 Natoque St.', city: 'Te Puke', state: 'NJ', zip: '87968', upvote: 499, downvote: 57)
Restaurant.create!(name: 'Non Quam', address: '8439 Interdum. Ave', city: 'Tay', state: 'OR', zip: '11272', upvote: 316, downvote: 210)
Restaurant.create!(name: 'Ut Quam Vel', address: '3470 Lobortis Ave', city: 'Campinas', state: 'SD', zip: '75955', upvote: 415, downvote: 46)
Restaurant.create!(name: 'Lorem', address: '289 Etiam Road', city: 'Hulst', state: 'AL', zip: '73504', upvote: 228, downvote: 18)
Restaurant.create!(name: 'Tortor Nunc', address: '7439 Convallis St.', city: 'Ararat', state: 'WA', zip: '29037', upvote: 368, downvote: 309)
Restaurant.create!(name: 'Hendrerit', address: '8513 Nisl Rd.', city: 'Graz', state: 'CA', zip: '04010', upvote: 119, downvote: 25)
Restaurant.create!(name: 'Primis', address: '3912 Vitae Street', city: 'Caucaia', state: 'CA', zip: '17434', upvote: 242, downvote: 154)
Restaurant.create!(name: 'Non Enim Mauris', address: '468 Orci, Street', city: 'Chilliwack', state: 'OK', zip: '85335', upvote: 481, downvote: 385)
Restaurant.create!(name: 'In', address: '4826 Ipsum St.', city: 'Katihar', state: 'CA', zip: '39773', upvote: 205, downvote: 304)
Restaurant.create!(name: 'Ut Cursus Luctus', address: '3168 Vulputate Rd.', city: 'Goes', state: 'WA', zip: '84418', upvote: 98, downvote: 297)
Restaurant.create!(name: 'Mauris Suspendisse Aliquet', address: '4260 Nec Rd.', city: 'Langenburg', state: 'AR', zip: '17397', upvote: 19, downvote: 168)
Restaurant.create!(name: 'Adipiscing Enim', address: '2744 A Ave', city: 'Rocky View', state: 'AZ', zip: '85597', upvote: 79, downvote: 437)
Restaurant.create!(name: 'Sit', address: '8122 Et, St.', city: 'Lac-Serent', state: 'OR', zip: '52353', upvote: 404, downvote: 291)
Restaurant.create!(name: 'Convallis Convallis', address: '2306 Curabitur Avenue', city: 'Vienna', state: 'MA', zip: '25085', upvote: 376, downvote: 378)
Restaurant.create!(name: 'Lorem Vitae', address: '3364 Aliquam Avenue', city: 'Huissen', state: 'GA', zip: '74013', upvote: 189, downvote: 46)
Restaurant.create!(name: 'Donec Egestas Duis', address: '4799 Dictum. Ave', city: 'Karapınar', state: 'KY', zip: '28649', upvote: 320, downvote: 419)
Restaurant.create!(name: 'Mollis Lectus', address: '8008 Nisi Road', city: 'Mataró', state: 'CA', zip: '80951', upvote: 343, downvote: 285)
Restaurant.create!(name: 'Dis Parturient', address: '569 Risus Road', city: 'Piovene Rocchette', state: 'OH', zip: '14779', upvote: 36, downvote: 27)
Restaurant.create!(name: 'Enim', address: '15238 Phasellus Avenue', city: 'Darwin', state: 'SC', zip: '78135', upvote: 345, downvote: 298)
Restaurant.create!(name: 'Eget', address: '168 Et Road', city: 'Dublin', state: 'CA', zip: '26097', upvote: 382, downvote: 376)
Restaurant.create!(name: 'Tellus Faucibus', address: '1855 Ut, Avenue', city: 'Gander', state: 'GA', zip: '41187', upvote: 267, downvote: 87)
Restaurant.create!(name: 'Viverra Donec Tempus', address: '1816 Orci. Rd.', city: 'Bhagalpur', state: 'Bihar', zip: '42132', upvote: 67, downvote: 150)
Restaurant.create!(name: 'Proin Nisl Sem', address: '6519 Sit Street', city: 'Geertruidenberg', state: 'TN', zip: '76300', upvote: 41, downvote: 308)
Restaurant.create!(name: 'Morbi', address: '5670 Magna Street', city: 'Helmond', state: 'NA', zip: '33022', upvote: 146, downvote: 25)
Restaurant.create!(name: 'Ac Mattis', address: '2084 At Rd.', city: 'Malahide', state: 'FL', zip: '88116', upvote: 202, downvote: 29)
Restaurant.create!(name: 'Orci In', address: '7141 Turpis Ave', city: 'Legnica', state: 'ND', zip: '57924', upvote: 456, downvote: 272)
Restaurant.create!(name: 'Lorem', address: '4468 Euismod St.', city: 'San Rafael', state: 'AR', zip: '49345', upvote: 125, downvote: 46)
Restaurant.create!(name: 'Neque', address: '1465 Fusce Avenue', city: 'Alacant', state: 'VA', zip: '95432', upvote: 406, downvote: 380)
Restaurant.create!(name: 'Magna', address: '2755 Felis. Road', city: 'Dunfermline', state: 'FL', zip: '63214', upvote: 335, downvote: 370)

